# Smoothie runtime configuration.
# Paths must be absolute or start with ~/ (expanded to the user home directory).

smoothie.input.base=~/ANTS/smoothie/networks/topology-zoo
conpanna.traces.dir=~/ANTS/smoothie/sigcomm26/plans/FM2RR/fd
smoothie.networks.cornetto=~/ANTS/cornetto/dataset/main_dataset/scenario-055/final_configs/configs
