# Smoothie runtime configuration.
# Paths must be absolute or start with ~/ (expanded to the user home directory).

smoothie.input.base=~/ANTS/smoothie/networks/topology-zoo
smoothie.output.base=~/ANTS/batfish/projects/smoothie/outputs/topology-zoo
snowcap.traces.dir=~/ANTS/snowcap/smoothie/zoo/traces
conpanna.traces.dir=~/ANTS/smoothie/sigcomm26/plans/FM2RR/fd
smoothie.topologies.dir=~/ANTS/snowcap/eval_sigcomm2021/topology_zoo
smoothie.networks.example=~/ANTS/batfish/networks/example/candidate/configs
smoothie.networks.internet2=~/ANTS/batfish/projects/smoothie/inputs/internet2-bagpipe-cleaned/configs
smoothie.networks.cornetto=~/ANTS/cornetto/dataset/main_dataset/scenario-055/final_configs/configs
